### PR TITLE
Update libgit2 to v28 to possibly resolve travis failures

### PR DESCRIPTION
**Pull request by catskul**

### CODE REVIEW

**Comment by catskul** [comment]
I apparently don't understand tox+travis, but all the builds have been failing.

**Comment by catskul** [comment]
Couldn't figure this out.

**Comment by aspiers** [comment]
Thanks a lot for trying. I managed to get it fixed now.

**Comment by waldyrious** [comment]
> I managed to get it fixed now.

Just for reference, the fix was done in #106.

**Pull request closed without merging**
